### ISSUE TITLE
NameError: global name 'basestring' is not defined (python 3)

### ISSUE THREAD

**Issue by rodrigorznd** [chiangf/Flask-Elasticsearch#11]
Version 0.2.4 start raise below exception

```
if isinstance(ctx.app.config.get('ELASTICSEARCH_HOST'), basestring):
NameError: name 'basestring' is not defined
```

please see the solution below, it works for me
https://github.com/oxplot/fysom/issues/1

**Comment by chiangf** [comment]
You're totally right, fixed it in 0.2.5, thanks!
