### ISSUE TITLE
Could you please go over why you have __getattr__?

### ISSUE THREAD

**Issue by rlam3** [chiangf/Flask-Elasticsearch#12]
Could you please provide me with an explanation of why you need this inside of your code? What does this actually do? I'm a bit confused here. Thanks!

``` python

    def __getattr__(self, item):
        ctx = stack.top
        if ctx is not None:
            if not hasattr(ctx, 'elasticsearch'):
                if isinstance(ctx.app.config.get('ELASTICSEARCH_HOST'), str):
                    hosts = [ctx.app.config.get('ELASTICSEARCH_HOST')]
                elif isinstance(ctx.app.config.get('ELASTICSEARCH_HOST'), list):
                    hosts = ctx.app.config.get('ELASTICSEARCH_HOST')
                ctx.elasticsearch = Elasticsearch(hosts=hosts,
                                                  http_auth=ctx.app.config.get('ELASTICSEARCH_HTTP_AUTH'),
                                                  **self.elasticsearch_options)

            return getattr(ctx.elasticsearch, item)

```

**Comment by chiangf** [comment]
Basically, if you follow the example in the README, you'll have this `es` object. At that point, you can use it like you would use `es` object in the elasticsearch-py examples (https://elasticsearch-py.readthedocs.io/en/master/)

When you call something like `es.index(...)` (or whatever you want), the `__getattr__` will be called and if the Elasticsearch object will be instantiated lazily if it doesn't already exist.
