### ISSUE TITLE
Not suppporting python3 ?

### ISSUE THREAD

**Issue by yashkumaratri** [chiangf/Flask-Elasticsearch#17]
Pip install Flask-Elasticsearch but when I import it it throws this error
`ModuleNotFoundError: No module named 'flask.ext'`
Is this not compatible with python3 or ?

**Comment by juniors90** [comment]
```
from flask import Flask
from flask_elasticsearch import FlaskElasticsearch

app = Flask(__name__)
es = FlaskElasticsearch(app)
```
