### ISSUE TITLE
Elasticsearch flask extension cannot support SSL

### ISSUE THREAD

**Issue by nelsnelson** [chiangf/Flask-Elasticsearch#3]
It _could_ support SSL, but it doesn't currently, because there is no way to add the keyword arguments to the Elasticsearch(...) instantiation at https://github.com/chiangf/Flask-Elasticsearch/blob/master/flask_elasticsearch.py#L34.

In order to support this, I'll create a patch.

**Comment by nelsnelson** [comment]
Patch: https://github.com/chiangf/Flask-Elasticsearch/pull/4

**Comment by chiangf** [comment]
Merged #4

**Comment by nelsnelson** [comment]
Thank you, sir.  I, however, did not include a version bump in setup.py.  :-(

**Comment by chiangf** [comment]
No worries, I've bumped it, thanks for the pull request!
