### ISSUE TITLE
es object : TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by johaven** [chiangf/Flask-Elasticsearch#5]
app = Flask(**name**)
es = FlaskElasticsearch(app)
print es.search(index="myindex", body={"query": {"match": {'message':'error'}}})
TypeError: 'NoneType' object is not callable

Flask version : 0.10.1
elasticsearch : 1.6.0
Flask-ElasticSearch : last

**Comment by abroekhof** [comment]
You need to be in app context, so either start a request or use: 

```
with app.app_context():
    print es.search(index="myindex", body={"query": {"match": {'message':'error'}}})
```
