### ISSUE TITLE
pypi still got version 0.2.1

### ISSUE THREAD

**Issue by rissoa** [chiangf/Flask-Elasticsearch#6]
I need pass extras parameters to Elasticsearch instance, I check the master branch, already supported, but have not pack and upload to pypi yet(still got 0.2.1 in pypi), pls update it :)

**Comment by alejoar** [comment]
Came here to say this. Can the pypi package be updated?

**Comment by bhairav13** [comment]
Also looking for the latest version updated so that I could pass extra parameters.  Thanks.

**Comment by rlam3** [comment]
+1

**Comment by chiangf** [comment]
Bumped to 0.2.3, let me know if you still get the old version, thanks!

**Comment by alejoar** [comment]
Thank you chiangf, got 0.2.3! :thumbsup::thumbsup:

**Comment by bhairav13** [comment]
Works great!  Thank you.
