### ISSUE TITLE
How does one go about indexing our models in production? 

### ISSUE THREAD

**Issue by rlam3** [chiangf/Flask-Elasticsearch#9]
How does one go about indexing our models in production? I'm looking at https://github.com/elastic/elasticsearch-dsl-py. Will there be more integration with high level api for this repo?

**Comment by chiangf** [comment]
@rlam3 You can look at the docs at https://elasticsearch-py.readthedocs.org/en/master/ to see, there's a section on indexing.

This extension just provides access to elasticsearch from within flask. My personal opinion with something like elasticsearch is that it's best to have full access to all the low-level functionalities, so I'm not planning any high-level APIs on top of this.
